### ISSUE TITLE
Windows threat detector keeps flagging the exe from release 0.2.7 as a trojan

### ISSUE THREAD

**Issue by Crimson-Wildfire** [kay-el-zed/HaloMCC-DiscordRPC#13]
whenever I download the exe from the latest release chrome downloader gives the '_failed - virus detected'_ error and windows threat protection gives me a notice with an error reading '_Trojan:Win32/Wacatac.B!ml_' saying its a trojan. I'm that not knowledgeable with code let alone software development but I know something like this isn't to be taken lightly. I know what happens when this isn't stopped, credit cards, accounts, personal details. stolen. I'm hoping this is just one of those times with an incorrect flag and this is a semi-common problem with a workaround

**Comment by Gurrman375** [comment]
Use this version: https://github.com/Gurrman375/HaloMCC-DiscordRPC/releases/tag/0.3.3. Kal has yet to updated the this own build. Also this app is designed to steal anything so make sure to only get this app from guthub.

Which version of windows are you using? (64 bit vs 32 bit and Intel v AMD)

**Comment by kay-el-zed** [comment]
Hi there, 

As Gurrman375 said, my releases have been lagging behind his due to not having much free time to work on the project. I highly recommend looking at his fork, linked above, for more up to date releases.

As for Windows Defender, it's likely that the python packager that was in use at the time is causing it to detect is as a false positive. The code base at the time of 0.2.7's release is completely safe, and interestingly enough, Windows Defender on my PC (AMD, x64, Win10 20H2) does not see it as malicious. Out of an abundance of caution however, I've removed the release. 

Apologies for the inconvenience and any scare that this might've given you. Gurrman has put in a ton of work in his fork to improve on it, and I highly recommend checking out his releases.

Thanks,
kay-el-zed.

**Comment by Gurrman375** [comment]
I typically built on amd so intel might show some false positives.
